### PR TITLE
[WIP] feat: lazy-load feature modules

### PR DESCRIPTION
**Pull request by manoldonev**
Add support for lazy loading feature modules.

Related to https://github.com/angular/angular/issues/10981
Related to https://github.com/angular/angular/issues/24657

### CODE REVIEW

**Comment by MartoYankov** [comment]
Just to note - there is currently no performance benefit from converting these modules to lazy loaded. They are all used as a default route in the router.

**Comment by manoldonev** [comment]
@ventsislav-georgiev It seems supporting lazy loading modules in tabview is a lot trickier at the moment than expected.

Our original tabview setup looks like this (uses only named/auxiliary outlets):
``` html
<TabView androidTabsPosition="bottom">

    <page-router-outlet
        *tabItem="{title: 'Home', iconSource: getIconSource('home')}"
        name="homeTab">
    </page-router-outlet>

    <page-router-outlet
        *tabItem="{title: 'Browse', iconSource: getIconSource('browse')}"
        name="browseTab">
    </page-router-outlet>

    <page-router-outlet
        *tabItem="{title: 'Search', iconSource: getIconSource('search')}"
        name="searchTab">
    </page-router-outlet>

</TabView>
```

With lazy loading we would like the AppModule routing config to look like this:
``` ts
const routes: Routes = [
    { path: "", redirectTo: "/(homeTab:home//browseTab:browse//searchTab:search)", pathMatch: "full" },

    { path: "home", outlet: "homeTab", loadChildren: "./home/home.module#HomeModule" },
    { path: "browse", outlet: "browseTab", loadChildren: "./browse/browse.module#BrowseModule" },
    { path: "search", outlet: "searchTab", loadChildren: "./search/search.module#SearchModule" }
];
```

However, [it seems](https://github.com/angular/angular/blob/fda30cb3e3e1f34361327b794ba2ef59d866b880/packages/router/src/config.ts#L487) that in such scenarios with componentless routes, lazy loaded modules, and named outlets Angular automatically plugs-in EmptyOutletComponent (i.e. `<router-outlet></router-outlet>`). Currently there is no option to customize this behavior e.g. we would like to plug `<page-router-outlet></page-router-outlet>` instead -- there is an open feature request [here](https://github.com/angular/angular/issues/24657). We thought we found a workaround for the inability to customize this Angular behavior by [introducing NsEmptyOutletComponent](https://github.com/NativeScript/template-tab-navigation-ng/pull/85/commits/64444054405000a8ea13329fca3ddc3ff49b87a1) (basically dummy component with `<page-router-outlet></page-router-outlet>` template) and changing the AppModule routing config like this:
``` ts
const routes: Routes = [
    { path: "", redirectTo: "/(homeTab:home//browseTab:browse//searchTab:search)", pathMatch: "full" },

    { path: "home", component: NsEmptyOutletComponent,
      outlet: "homeTab", loadChildren: "./home/home.module#HomeModule" },
    { path: "browse", component: NsEmptyOutletComponent,
      outlet: "browseTab", loadChildren: "./browse/browse.module#BrowseModule" },
    { path: "search", component: NsEmptyOutletComponent,
      outlet: "searchTab", loadChildren: "./search/search.module#SearchModule" }
];
```

But this essentially sets up a use case with nested page router outlets that is not supported properly at the moment in NativeScript -- open feature request [here](https://github.com/NativeScript/nativescript-angular/issues/1351). It does not work most obviously on Android where two ActionBars are visible at a time (same for iOS but not so obvious).

So currently this PR can only introduce limited support for lazy loaded modules in tab items:
1) If navigation within a tab is not used (i.e. no item->detail and back pattern) there are no restrictions on lazy loading modules (and page router outlet naming)
2) If navigation within a tab is used (i.e. item->detail and back pattern) such module can be lazy loaded ONLY IF it is loaded in the PRIMARY (unnamed) page router outlet


Also, to reiterate @MartoYankov comment -- currently there would be no performance benefit from lazy loading the tab modules as all of them are used as a default route in the router `{ path: "", redirectTo: "/(homeTab:home//browseTab:browse//searchTab:search)", pathMatch: "full" },`.

**Comment by manoldonev** [comment]
@MartoYankov as discussed tested [second-level lazy loaded module](https://github.com/NativeScript/template-tab-navigation-ng/commit/9f9b63c840ffb1c6c55b71750f47b3cfbce5f18a) that would provide performance benefit as it would not be loaded as part of the default route if one has complex hierarchy below "item detail" -- generally works but would have the same limitations related to nested page router outlets if "item detail" implements navigation on its own.

**Comment by tskweres** [comment]
:(

**Comment by MartoYankov** [comment]
@tskweres This will probably get in with {N} 5.0 which will come out at the end of October. We need to be able to nest page-router-outlets.

**Comment by ronaiza-cardoso** [comment]
@MartoYankov any work on this?

**Comment by manoldonev** [comment]
This PR https://github.com/NativeScript/NativeScript/pull/6528 should address the pending Android issue with back navigation after app suspend/resume.

**Comment by ronaiza-cardoso** [comment]
amazing job @manoldonev, I've been fallowing all your commits on this. Thanks for that!

**Pull request merged**
